server:
  port: 8001

# 配置eureka服务注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    hostname: localhost

# 指定应用名称
spring:
  application:
    name: eureka-client
